
erver:
  port: 3004
  servlet:
    context-path: /transaction
  error:
    include-message: always
spring:
  application:
    name: transaction-service
  data:
    mongodb:
      host: ${DB_UPSTREAM}
      port: 27017
      database: transactions
      # NOT NEEDED FOR LOCAL INSTANCE
  #      username: rootmongo
  #      password: rootmongo
  #      authentication-database: admin

# Eureka props
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eurekaUser:eurekaPass@discovery-service:3007/eureka/

jwt:
  secret: s3cr3t
  header: Authorization
  expiration: 3600